# Generated by Django 4.2.3 on 2024-07-25 19:57

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=blog.models.UploadFile.directory)),
            ],
        ),
        migrations.CreateModel(
            name='Hyperreactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinid', models.CharField(max_length=20)),
                ('cysteineid', models.CharField(max_length=20)),
                ('resid', models.CharField(max_length=20)),
                ('weerapana_mean', models.FloatField(null=True)),
                ('palafox_mean', models.FloatField(null=True)),
                ('vinogradova_mean', models.FloatField(null=True)),
                ('cysdb_mean', models.FloatField(null=True)),
                ('cysdb_median', models.FloatField(null=True)),
                ('cysdb_stdev', models.FloatField(null=True)),
                ('cysdb_reactivity_category', models.CharField(max_length=5)),
                ('hyperreactive', models.CharField(max_length=20)),
                ('castellon_mean', models.FloatField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.uploadfile')),
            ],
        ),
        migrations.CreateModel(
            name='Cysdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('proteinid', models.CharField(max_length=20)),
                ('cysteineid', models.CharField(max_length=20)),
                ('resid', models.CharField(max_length=20)),
                ('datasetid', models.CharField(max_length=20)),
                ('identified', models.CharField(max_length=20)),
                ('identified_datasets', models.CharField(max_length=20)),
                ('ligandable_datasets', models.CharField(max_length=20)),
                ('ligandable', models.CharField(max_length=20)),
                ('cell_line_datasets', models.CharField(max_length=20)),
                ('hyperreactive', models.CharField(max_length=20, null=True)),
                ('hyperreactive_datasets', models.CharField(max_length=20, null=True)),
                ('redox_datasets', models.CharField(max_length=20, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.uploadfile')),
            ],
        ),
    ]
