# Generated by Django 4.2.3 on 2024-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperreactive',
            name='new_means',
            field=models.JSONField(default=dict),
        ),
    ]
